Redisenio
algoritmos-rw/algoritmos-rw.github.io pull request #1
Opened 2017-10-03 02:15 UTC by Florencia-97

# Portal entrada cursos de Rosita Wachenchauzer 

 Página principal de todos los cursos de Rosita, con una pequeña introducción al curso y un link al sitio de la materia descripta. 

## Cursos
Para la adición de un nuevo curso se debe crear un nuevo archivo en la carpeta _post del tipo markdown (md) con el siguiente formato. 

>.---
>codigo: código de la materia
titulo: Titulo de la materia
sitio: link a la página del materia
descripcion: Descripción del curso
lenguajes: Lenguajes utilizados en el curso
imagen: dirección de la imagen que se desea colocar
color:  color en formato rgb del box dónde estará toda la info
.---

## Modificación de contenido:
### Información:
 Solo se debe dirigir al archivo md ( en _posts) correspondiente a la materia y modificar los datos deseados ahí.
### Diseño:
* Fondo: cambiar la imagen en la style.css de header.cabezera.
* Font : Agregar una nueva font ( en la carpeta fonts) y modificar en style.css el url de @font-face.
* Background: Cambiar el fondo de la página modificando en style.css el background_image del body.

## Imagenes

![whatsapp image 2017-10-02 at 22 33 19](https://user-images.githubusercontent.com/20881323/31107106-862adb3a-a7c6-11e7-9b21-4eae1a0fbf15.jpeg)

#### Una foto antes y otra después:
![whatsapp image 2017-10-02 at 22 33 19 1](https://user-images.githubusercontent.com/20881323/31107107-862b5146-a7c6-11e7-806e-55b81f07236c.jpeg)

2017-10-03 04:08 UTC, dato commented
Por si les sirve como mejoras, les he dejado unas simplificaciones en https://github.com/algoritmos-rw/algoritmos-rw.github.io/pull/2.

2017-10-03 13:18 UTC, FdelMazo commented
Ya aceptadas e incorporadas las sugerencias de @dato habría que eliminar esa branch (no lo hago yo por si quiere seguir sugiriendo).

De ser mergeada, falta quitar los lorem ipsums de TDA y TDA2 ya que nosotros no cursamos esas materias.

2017-10-03 16:24 UTC, dato commented
Desde el punto de vista técnico (Jekyll etc.) la PR está bien; pero prefiero que den el merge approval @fbarrios o @mbuchwald.

2017-10-03 19:05 UTC, fbarrios commented
En bajas resoluciones se rompe:

![image](https://user-images.githubusercontent.com/5757489/31143726-9020dd86-a854-11e7-993a-bb2a32e4f411.png)

2017-10-04 02:58 UTC, dessaya approved these changes

2017-10-04 13:59 UTC, Florencia-97 commented
Ahora no debería romperse el título en bajas resoluciones.

2017-10-10 15:31 UTC, fbarrios requested changes

2017-10-10 15:31 UTC, fbarrios commented on Makefile
> +	apt-get install ruby ruby
`ruby ruby` > `ruby`

2017-10-10 15:31 UTC, fbarrios commented on _layouts/home.html
> +    <p class="kicker">Facultad de Ingeniería de Buenos Aires</p>
"Facultad de Ingeniería de Buenos Aires" > "Facultad de Ingeniería, Universidad de Buenos Aires"

2017-10-10 15:31 UTC, fbarrios commented on _data/materias.yml
> +  descripcion: Curso en el que se busca introducir a los alumnos a la programación
Cambiaría esta descripción por algo similar a lo que está en la planificación: http://www.fi.uba.ar/sites/default/files/7540-544.pdf

> Aprender a diseñar e implementar programas sencillos, introduciendo la noción de recursos en tiempo y espacio.

2017-10-10 15:31 UTC, fbarrios commented on _data/materias.yml
> +  lenguajes: Python
¿Es necesario lo del lenguaje? No sé si está bien ponerlo como un feature de un curso cuando en realidad siempre hablamos de que es una herramienta :)

2017-10-10 15:31 UTC, fbarrios commented on _data/materias.yml
> +  descripcion: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
De http://www.fi.uba.ar/sites/default/files/7541-533.pdf

> Introducir los conceptos de diseño de algoritmos y de estructuras de datos, utilizando nociones de eficiencia algorítmica para poder seleccionar la solución más adecuada para un contexto dado.

2017-10-10 15:31 UTC, fbarrios commented on _data/materias.yml
> +  descripcion: Curso en el que se busca introducir a los alumnos a la programación
(Y no debería ser "descripción" sino "objetivo")

2017-10-10 15:31 UTC, fbarrios commented on _data/materias.yml
> +  descripcion: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
> Profundizar las herramientas teóricas y prácticas para la evaluación del costo temporal y espacial de un algoritmo analizando diversas técnicas de diseño de algoritmos en la manipulación de grandes volúmenes de información.

2017-10-10 15:31 UTC, fbarrios commented on _data/materias.yml
> +  descripcion: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
> "Estudiar algoritmos avanzados y estructuras de datos avanzadas."

2017-10-10 15:31 UTC, fbarrios commented on _data/materias.yml
> +  imagen: /assets/img/python.png
Siguiendo esa línea, en vez del logo del lenguaje pondría otra cosa. Por ejemplo una foto a un fragmento de código (de una búsqueda binaria?). ¿Qué opinan?

2017-10-10 15:31 UTC, fbarrios commented on _data/materias.yml
> +  imagen: /assets/img/clogo.png
Acá voy a buscar una imagen de una instancia de SAT o algún problema NP-Completo.

2017-10-10 15:31 UTC, fbarrios commented on _data/materias.yml
> +  imagen: /assets/img/clogo.png
¿Qué imagen es representativa de algo 2? ¿Un ABB?

2017-10-10 15:31 UTC, fbarrios commented on _data/materias.yml
> +  imagen: /assets/img/clogo.png
Y acá necesito una imagen de string matching.

2017-10-10 20:04 UTC, fbarrios commented
@Florencia-97 @FdelMazo Dado que los sitios en las materias son bastante más sobrios y con colores mucho más apagados, ¿les parece cambiar los colores para que se adapten más a los sitios?

Particularmente, estaría genial que me dejen los fondos de color blanco, así busco / hago imágenes que peguen.

2017-10-10 20:13 UTC, FdelMazo commented
Si. Esa era nuestra otra alternativa. Todas gamas de negros y blancos (cremas, grises, etc). El sabado nos ibamos a juntar a verlo bien. Si en el medio conseguís fotos/logos mostranos y nos adaptamos a eso

2017-10-15 05:31 UTC, FdelMazo commented
# Rediseño del rediseño

![screenshot 2017-10-15 11](https://user-images.githubusercontent.com/25667102/31582096-cb5ced2c-b150-11e7-9199-873e2777cfdc.png)

Cambiados todo lo dicho por @fbarrios.
* Typos

* Sacado lo del lenguaje

* Cambiados los logos

* Cambiados los colores (y el header para matchear)

# Known Issues

A mi me gustaria que quede más uniforme el objetivo de cada materia, algunos son muy largos y otros muy cortos. Algo más para escribir de TDA2?

Las fotos son placeholders, si se les ocurren o diseñan otras, se pueden cambiar, en particular acerca de las dos TDA, que no estoy seguro de que estoy buscando. Son cuadradas (definido en main.scss)

2017-10-16 04:41 UTC, fbarrios commented
¿Soy muy minimalista con una contrapropuesta así?

![image](https://user-images.githubusercontent.com/5757489/31595562-0f010b7c-b213-11e7-91b0-916077d5bf4b.png)

2017-10-24 07:30 UTC, Xero-Hige commented
Sos muy muchas cosas con esa propuesta @fbarrios . El blaco es como muy brillante, me convence mas la alternativa con banner porque es menos cansador a la vista. Lo único que no me convence la combinacion de colores de los recuadros.
En particular, me gusta mas el banner de la primera versión, que si bien es menos sobrio le da un poco mas de vida. De ultima se puede hacer con los mismos colores pero menos brillo (pero solo de la capa de colores).

2017-10-26 01:56 UTC, Florencia-97 commented
Por lo comentado por Gastón, cambiamos el color de las cuatro materias  por uno solo.
![cremados](https://user-images.githubusercontent.com/20881323/32031465-b1646078-b9d7-11e7-82f3-1e36829d83be.png)

2017-10-26 02:25 UTC, Xero-Hige approved these changes

2018-11-21 13:00 UTC, closed without merging